# File: amu/admin/config.yml

backend:
  name: github
  repo: kelar89/amu # PASTIKAN INI SESUAI: username/nama-repo Anda
  branch: main
  auth_type: "pkce"
  app_id: Ov23liEdWEAM69zrTHqT # GANTI DENGAN CLIENT ID DARI GITHUB

media_folder: "img"
public_folder: "/img"

collections:
  - name: "projects"
    label: "Portfolio Projects"
    folder: "_data/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "URL", name: "url", widget: "string", required: false}

  - name: "reviews"
    label: "Client Reviews"
    folder: "_data/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Quote", name: "quote", widget: "text"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Origin", name: "origin", widget: "string"}
      - {label: "Avatar", name: "avatar", widget: "image"}